
store:
  serviceRegistry:
    userName: serviceRegistry
    password: 'ead123sr'
  auth:
    jwtSecret: a3a6b9ac04baeec1ae14bf264753d0ab1141ca0519bd5ff696a8fcd50c6ff9d2bb9d8ce7b53e6141091fb66f0076f86b9a6d8512d6edbd8f29305ca09f53d2a3
    jwtExpirationMs: 14400000
      
management:
  endpoints:
    web:
      exposure:
        include: health      