server:
  port: 8761

spring:
  application:
    name: store-service-registry

store:
 serviceRegistry:
   userName: serviceRegistry
   password: 'ead123sr'

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost