server:
  port: 8080

spring:
  application:
    name: store-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user_service
          uri: lb://store-user-service
          predicates:
            - Path=/store_user/**