server:
  port: 8080

spring:
  application:
    name: store-api-gateway
  cloud:
    gateway:   
      server:
        webflux:          
          routes:
            - id: user_service
              uri: lb://store-user-service
              predicates:
                - Path=/store_user/**                          